server:
  port: 8002

spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  data:
    redis:
      host: 192.168.200.200
      port: 6379
shortlink:
  group:
    create:
      # 用户最多创建的分组数量
      max: 10
  # 封控
  flow:
    # 是否开启封控
    enable: true
    # 每几秒内单个用户
    timeWindow: 1
    # 最大请求数量
    maxAccessCount : 5
