server:
  port: 8001
spring:
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  data:
    redis:
      host: 192.168.200.200
      port: 6379
  rabbitmq:
    host: 192.168.200.200
    port: 5672
    virtual-host: shortlink # 虚拟机地址 我们docker安装的时候默认设置的是itheima，这里我们可以自己创建
    username: shortlink
    password: 123456
    listener:
      simple:
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始的失败等待时长为1秒
          multiplier: 2 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: false # true无状态；false有状态。如果业务中包含事务，这里改为false
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
shortlink:
  state:
    locale:
        key: d2ed0942a4c876a4d7bf8b666586d2e4
  domain:
    default: nurl.ink.com:8001
  goto-domain:
    white-list:
      enable: true
      names: '拿个offer,知乎,掘金,博客园,哔哩哔哩,CSDN中文网,GitHub'
      details:
        - nageoffer.com
        - zhihu.com
        - juejin.cn
        - cnblogs.com
        - bilibili.com
        - csdn.net
        - github.com